### PR TITLE
Add release event support

### PR DESCRIPTION
**Pull request by anayden**
Skip most of the "skip" logic for the `release` event

### CODE REVIEW

**Review by asvetlov — CHANGES_REQUESTED** [review]
Release event has no `head_branch` field.
The following code doesn't work:
```
head_branch = ctx["event"]["workflow_run"]["head_branch"]
if not skip:
    match = re.match(r"^v\d+\.\d+(\.\d+)?(?P<pre>(a|b|rc)\d*)?$", head_branch)
```
Please analyze payload type and add required changes: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release

**Comment by anayden** [comment]
@asvetlov 

> Release event has no head_branch field.

Your statement is correct, but the code anyway only runs on the `workflow_run` event:

```event_name = ctx["event_name"]
if event_name != "workflow_run":
    print(
        f"::error::Invalid event type {event_name}, "
        "release-image-action should be executed on 'workflow_run' event"
    )
    sys.exit(1)
```

Which means, the webhook payload is defined here https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

Maybe I misunderstand your comment?

**Comment by asvetlov** [comment]
`ctx["event"]["workflow_run"]["head_branch"]`  from https://github.com/neuro-inc/release-image-action/pull/43/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R53 fails with `KeyError`.

How do you would to proceed it?

**Comment by anayden** [comment]
I don't understand why event `workflow_run` would not have the `head_branch` key:

According to  https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run:

Untitled

**Comment by asvetlov** [comment]
IIRC workflow_run describes the parent workflow.
`pull_request` workflow definitely has `head_branch`.
I doubt if `release` workflow has it.
You can try though

**Comment by anayden** [comment]
Closing as not-needed

**Pull request closed without merging**
